#!/usr/bin/env bash
# get the record type of a domain
if [[ $# -eq 2 ]]; then
    dig_res=$(dig -t A "$2" | awk '/ANSWER SECTION/ {getline; print}')
    echo "$dig_res" | while read -ra token;
    do
        unset IFS
        IFS='.' read -ra subdomain <<< "${token[0]}"
        echo "The subdomain ${subdomain[0]} is a ${token[3]} record and points to ${token[4]}"
    done
fi
if [[ $# -eq 1 ]]; then
    subs=('www' 'lb-01' 'web-01' 'web-02')
    for sub in "${subs[@]}";
    do
        dig_res=$(dig -t A "$sub.$1" | awk '/ANSWER SECTION/ {getline; print}')
        echo "$dig_res" | while read -ra token;
        do
            unset IFS
            IFS='.' read -ra subdomain <<< "${token[0]}"
            echo "The subdomain $sub is a ${token[3]} record and points to ${token[4]}"
        done
    done
fi
